const crimes = [
  "pickpocketed someone",
  "robbed a bank",
  "shoplifted from a store",
  "carjacked a vehicle",
  "hacked into a bank account",
  "forged checks",
  "held up a convenience store",
  "stole a valuable artifact",
  "broke into a safe",
  "smuggled cash",
  "bribed a politician",
  "printed counterfeit money",
  "boarded a cargo ship for cash",
  "won a rigged poker game",
  "extorted money from someone",
  "evaded taxes",
  "ran an underground casino",
  "stole someone's financial identity",
  "ransacked a wealthy estate",
  "sold illegal financial securities",
  "embezzled funds from a company",
  "plundered a treasure vault",
  "siphoned money from a charity",
  "hijacked an armored truck",
  "swindled investors in a Ponzi scheme",
  "kidnapped a wealthy individual for ransom",
  "hacked into an offshore account",
  "looted a casino vault",
  "stole bearer bonds from a facility",
  "extorted protection money",
  "coerced wire transfers from victims",
  "fleeced tourists with a sophisticated scam",
  "skimmed profits from an illegal business",
  "diverted funds from government projects",
  "robbed a high-stakes gambling den",
  "engaged in insider trading",
  "conducted an art heist",
  "forged identities to access bank accounts",
  "conducted a cyber heist",
  "smuggled diamonds and metals",
  "looted a crypto exchange",
  "kidnapped a crypto trader for ransom",
  "siphoned funds from decentralized finances",
  "blackmailed a corporate executive for money",
  "stole confidential financial data",
  "hijacked a payment system",
  "looted a luxury yacht",
  "stole from a wallet",
  "held up a bank",
  "lifted from a shop",
  "carjacked a car",
  "forged signatures",
  "robbed a store",
  "stole an artifact",
  "cracked a vault",
  "bribed officials",
  "printed fake money",
  "boarded a ship",
  "rigged a game",
  "extorted funds",
  "evaded taxation",
  "ran a casino",
  "stole an ID",
  "ransacked an estate",
  "sold fake stocks",
  "embezzled funds",
  "plundered a vault",
  "siphoned donations",
  "hijacked a truck",
  "swindled investors",
  "kidnapped for ransom",
  "hacked accounts",
  "looted a casino",
  "stole bonds",
  "extorted businesses",
  "coerced transfers",
  "scammed tourists",
  "profited illegally",
  "diverted government funds",
  "traded illegally",
  "stole art",
  "forged documents",
  "committed cyber bank theft",
  "smuggled metals",
  "looted crypto",
  "kidnapped traders",
  "siphoned finance",
  "blackmailed executives",
  "stole data",
  "hijacked payments",
  "looted yachts",
];

module.exports = crimes;
