const professions = [
  "Painter",
  "Welder",
  "Policeman",
  "Policewoman",
  "Artist",
  "Rapper",
  "Singer",
  "Cashier",
  "Truck Driver",
  "Homeless Person",
  "Butcher",
  "Nerd",
  "Business man",
  "Developer",
  "Dentist",
  "Nurse",
  "Accountant",
  "Lawyer",
  "Plumber",
  "Electrician",
  "Astronaut",
  "Pilot",
  "Flight Attendant",
  "Photographer",
  "Architect",
  "Therapist",
  "Actor",
  "Fisherman",
  "Clerk",
  "Judge",
  "Teacher",
  "Teachers Aid",
  "Football Player",
  "Farmer",
  "CEO",
  "Business Owner",
  "First Responder",
  "Scientist",
  "Veteran",
  "Musician",
  "Baker",
  "Chef",
  "Beekeeper",
  "Bus Driver",
  "Garbage Man",
  "Carpenter",
  "Chemist",
  "Social Worker",
  "Construction Worker",
  "Author",
  "Illustrator",
  "Crossing Guard",
  "Metermaid",
  "Dancer",
  "Editor",
  "Broker",
  "Office Worker",
  "Lumberjack",
  "Coach",
  "Gamer",
  "Miner",
  "Graphic Designer",
  "Jeweler",
  "Hacker",
  "Scammer",
  "Librarian",
  "Lifeguard",
  "Military Officer",
  "Soldier",
  "Nuclear Engineer",
  "Engineer",
  "Orthodontist",
  "Park Ranger",
  "Mailman",
  "Mailwoman",
  "Hair Dresser",
  "Landscaper",
  "Sculptor",
  "Sewer",
  "Captain",
  "Stripper",
  "Bank Teller",
  "Mechanic",
  "Tutor",
  "Vet",
  "Woodworker",
  "Chiropractor",
  "Data Analyst",
  "Event Planner",
  "Geologist",
  "Interpreter",
  "Marketing Specialist",
  "Nutritionist",
  "Personal Trainer",
  "Public Relations Specialist",
  "Real Estate Agent",
  "Software Engineer",
  "Translator",
  "Video Editor",
];

module.exports = professions;
